.PHONY: clean All

All:
	@echo "----------Building project:[ ExpandBatteryDataFile - Debug ]----------"
	@cd "ExpandBatteryDataFile" && "$(MAKE)" -f  "ExpandBatteryDataFile.mk"
clean:
	@echo "----------Cleaning project:[ ExpandBatteryDataFile - Debug ]----------"
	@cd "ExpandBatteryDataFile" && "$(MAKE)" -f  "ExpandBatteryDataFile.mk" clean
