.PHONY: clean All

All:
	@echo "----------Building project:[ BatteryLifetimePrediction - Release ]----------"
	@cd "BatteryLifetimePrediction" && "$(MAKE)" -f  "BatteryLifetimePrediction.mk"
clean:
	@echo "----------Cleaning project:[ BatteryLifetimePrediction - Release ]----------"
	@cd "BatteryLifetimePrediction" && "$(MAKE)" -f  "BatteryLifetimePrediction.mk" clean
